spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zsf_ku
    username: ZSF
    password: ZSF
  jpa:
    show-sql: true
    generate-ddl: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    restart:
      enabled: true
logging:
  level:
    root: info
    com.lottery: debug
